### ISSUE TITLE
Doesn't show test announcements of Python script

### ISSUE THREAD

**Issue by krisutofu** [amosproj/amos2021ws07-nft-development#245]
Issue tracker is **ONLY** used for reporting bugs. 

## Expected Behavior

After initializing my announcement collection for appwrite, I can see the test announcement created there.

## Current Behavior

When the announcement database is created/initialized with the Python Script `createAnnouncementCollection.py` and the Collection ID is set to it, it won't display the initialized announcements.

## Possible Solution

Please see Dominics response below.

## Steps to Reproduce

1. run Appwrite and set environment variables properly (read the documentation therefor)
2. call createAnnouncementCollection.py and set APPWRITE_ANNOUNCEMENT_ID appropriately for the frontend.
3. restart the application and load the landing page

## Context (Environment)

I wanted to display my test announcements instead of recreating them everytime.

## Detailed Description

This problem didn't always exist. I remember having seen a version of Que where they were displayed.

I tried to load single announcement documents by their document ID listed in Appwrite but they couldn't be found. Seems to be a bug in Appwrite itself??

**Comment by dominic-heil** [comment]
This is a backend bug. When the example announcements are created, they do not get passed a read permission. Only the whole collection gets read permissions, but not the individual documents of the DB. Additionally, the write permission of the collection is wrong. It cannot be ` ["team:Admins"]` but must be ` ["team:{adminsTeamId}"]`.

**Comment by krisutofu** [comment]
> This is a backend bug. When the example announcements are created, they do not get passed a read permission. Only the whole collection gets read permissions, but not the individual documents of the DB. Additionally, the write permission of the collection is wrong. It cannot be ` ["team:Admins"]` but must be ` ["team:{adminsTeamId}"]`.

Is this already fixed? Otherwise this could be added to my PR that still needs review by others.

**Comment by steinkohl** [comment]
> `["team:{adminsTeamId}"]`.

really? then i will edit the script again :sweat_smile:

**Comment by dominic-heil** [comment]
> > `["team:{adminsTeamId}"]`.
> 
> really? then i will edit the script again 😅

Not 100% sure. @krisutofu said it also worked for him if you just do team:Admins. When I tested that a few month ago it didn't work for me.

**Comment by krisutofu** [comment]
> > `["team:{adminsTeamId}"]`.
> 
> really? then i will edit the script again sweat_smile

Like Dominic mentions, "team:Admins" just works for me with v0.11. At least the test announcements are displayed. I don't know why. Better use the more stable solution that works for all.
