### ISSUE TITLE
GitHub workflow for backend linting

### ISSUE THREAD

**Issue by BerinikeTech** [amosproj/amos2021ws07-nft-development#27]
## User story
1. As a developer
2. I want a GitHub workflow that automatically lints the (Python) backend code on every push
3. So that uniform coding style is enforced

## Acceptance criteria
* GitHub workflow is created
* Workflow is tested with one of the implemented backend functionalities

**Comment by steinkohl** [comment]
Implementation also includes:
- Bandit security linting (avoid dangerous code patterns)
- Black formatter (only checks if correct format is given, actual formatting is done locally via pre-commit hook)
- Flake8 linter (checks code complexity)
- Pytest (tests python code and creates a ticket/issue if the required coverage isn't satisfied or a test fails)
