### ISSUE TITLE
Change team of a user

### ISSUE THREAD

**Issue by dominic-heil** [amosproj/amos2021ws07-nft-development#46]
## User story
1. As a website admin
2. I need to be able to change the team of a user
3. So that I can add new admins or assign users special roles.

## Acceptance criteria 
* The user data can be requested by the frontend to be displayed in the frontend.
* There is an endpoint that can change the teams of a user. The endpoint receives all the teams a user should have and after the update the user is assigned to these and only these teams.
* This functionality is implemented as an appwrite function that can be accessed through the appwrite API.
* This function can only be executed by admins.
* There should be a (Python) script that creates the function for appwrite if it does not yet exist.

**Comment by steinkohl** [comment]
All required functionalities are already fulfilled by the appwrite api.
The Team api provides methods to get, create and delete memberships (https://appwrite.io/docs/client/teams).
Precondition: At leased one user in the team 'Admins' with an 'owner' role (done via init-script).

Make someone admin -> a team member of 'Admins' with the role 'owner' can create a membership for user in team 'Admin', if the role of the new admin is also set to 'owner', the new admin also can make users to admins.
Remove somebody from 'Admins' team -> also only 'Admins' with 'owner' role can do that.
