### ISSUE TITLE
Get infrastructure ready

### ISSUE THREAD

**Issue by Floinko** [amosproj/amos2021ws07-nft-development#5]
## User story
1. As a developer
2. I want to have access to the project infrastructure
3. So that I can deploy my code there

## Acceptance criteria
* We have a response of the module  organisator or andre

**Comment by BerinikeTech** [comment]
Hi Nike,

as discussed in our call we would like to support you with server capacities. My colleague Yannick would like to have a call with you to understand what exactly you need...then we will of course make it possible ;-)
@Yannick Siewe: Feel free to add if needed!

If you have any questions, please feel free to contact me.

VG
Andre


Good morning everyone,

Thank @Andre Achtstaetter for the introduction, in fact, I would like to better understand the use case and thus provide the best infrastructure resources to meet the case.

I am generally open for meetings from Monday to Thursday in the afternoon, between 1 - 2 pm and 3 - 5 pm.

Looking forward to hearing from you
Yannick
